default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: avito_manager_development

test:
  <<: *default
  database: avito_manager_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch('DB_NAME', 'avito_manager_production') %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: avito_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: avito_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: avito_manager_production_cable
    migrations_paths: db/cable_migrate
